# Generated by Django 4.1.6 on 2023-02-12 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('total_easy', models.SmallIntegerField(default=614)),
                ('total_medium', models.SmallIntegerField(default=1335)),
                ('total_hard', models.SmallIntegerField(default=556)),
                ('weekly_contest_no', models.SmallIntegerField(default=323)),
                ('biweekly_contest_no', models.SmallIntegerField(default=93)),
                ('easy', models.JSONField(blank=True, null=True)),
                ('medium', models.JSONField(blank=True, null=True)),
                ('contest', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
