# Generated by Django 4.1.5 on 2023-01-19 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_leetcodedetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodechefDetail',
            fields=[
                ('date', models.DateField(auto_now=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='backend.profile')),
                ('global_rank', models.PositiveIntegerField(blank=True, null=True)),
                ('badges', models.JSONField(blank=True, null=True)),
                ('contest_participated_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('problems_solved', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CodeforcesDetail',
            fields=[
                ('date', models.DateField(auto_now=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='backend.profile')),
                ('friendOfCount', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('contestRating', models.PositiveIntegerField(blank=True, null=True)),
                ('totalProblemSolved', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('rank', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('winner1', models.CharField(blank=True, max_length=100, null=True)),
                ('winner2', models.CharField(blank=True, max_length=100, null=True)),
                ('winner3', models.CharField(blank=True, max_length=100, null=True)),
                ('winner4', models.CharField(blank=True, max_length=100, null=True)),
                ('winner5', models.CharField(blank=True, max_length=100, null=True)),
                ('imageUrl1', models.URLField(blank=True, max_length=400, null=True)),
                ('imageUrl2', models.URLField(blank=True, max_length=400, null=True)),
                ('imageUrl3', models.URLField(blank=True, max_length=400, null=True)),
                ('imageUrl4', models.URLField(blank=True, max_length=400, null=True)),
                ('imageUrl5', models.URLField(blank=True, max_length=400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GithubDetail',
            fields=[
                ('date', models.DateField(auto_now=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='backend.profile')),
                ('no_of_repositories', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('no_of_followers', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('no_of_following', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('tech_stack', models.JSONField(blank=True, null=True)),
                ('own_repo', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HackerrankDetail',
            fields=[
                ('date', models.DateField(auto_now=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='backend.profile')),
                ('followers_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('score_lang', models.PositiveIntegerField(blank=True, null=True)),
                ('badges', models.JSONField(blank=True, null=True)),
                ('certificates', models.JSONField(blank=True, null=True)),
                ('score_elo', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LinkedInDetail',
            fields=[
                ('date', models.DateField(auto_now=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='backend.profile')),
                ('img_url', models.CharField(blank=True, max_length=200, null=True)),
                ('aboutus', models.TextField(blank=True, null=True)),
                ('headline', models.CharField(blank=True, max_length=250, null=True)),
                ('geoLocationName', models.CharField(blank=True, max_length=200, null=True)),
                ('experience', models.JSONField(blank=True, null=True)),
                ('education', models.JSONField(blank=True, null=True)),
                ('certifications', models.JSONField(blank=True, null=True)),
                ('projects', models.JSONField(blank=True, null=True)),
                ('honors', models.JSONField(blank=True, null=True)),
                ('publications', models.JSONField(blank=True, null=True)),
                ('skills', models.JSONField(blank=True, null=True)),
                ('connectionsCount', models.SmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OfficeBearer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('position', models.CharField(max_length=70)),
                ('name', models.CharField(blank=True, max_length=70, null=True)),
                ('img', models.URLField(blank=True, max_length=400, null=True)),
                ('rank', models.SmallIntegerField(default=20, null=True)),
                ('present_academic_year', models.CharField(blank=True, choices=[('2020-2021', '2020-2021'), ('2021-2022', '2021-2022'), ('2022-2023', '2022-2023'), ('2023-2024', '2023-2024'), ('2024-2025', '2024-2025'), ('2025-2026', '2025-2026'), ('2026-2027', '2026-2027'), ('2027-2028', '2027-2028'), ('2028-2029', '2028-2029'), ('2029-2030', '2029-2030'), ('2030-2031', '2030-2031')], default='2', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('total_easy', models.SmallIntegerField(default=614)),
                ('total_medium', models.SmallIntegerField(default=1335)),
                ('total_hard', models.SmallIntegerField(default=556)),
                ('weekly_contest_no', models.SmallIntegerField(default=323)),
                ('biweekly_contest_no', models.SmallIntegerField(default=93)),
                ('easy', models.JSONField(blank=True, null=True)),
                ('medium', models.JSONField(blank=True, null=True)),
                ('contest', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
