# Generated by Django 4.1.5 on 2023-01-20 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_codechefdetail_codeforcesdetail_event_githubdetail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='dummycheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateTimeField(auto_now=True)),
                ('n', models.CharField(blank=True, max_length=60, null=True)),
            ],
        ),
    ]
