# Generated by Django 4.1.5 on 2023-01-20 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_dummycheck'),
    ]

    operations = [
        migrations.DeleteModel(
            name='dummycheck',
        ),
    ]
