# Generated by Django 4.1.6 on 2023-02-12 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UsersAndProfile', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewUser',
        ),
    ]
