# Generated by Django 4.1.6 on 2023-02-12 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UsersAndProfile', '0005_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('leetcode', models.CharField(blank=True, max_length=40, null=True)),
                ('github', models.CharField(blank=True, max_length=40, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=40, null=True)),
                ('hackerrank', models.CharField(blank=True, max_length=40, null=True)),
                ('codechef', models.CharField(blank=True, max_length=40, null=True)),
                ('codeforces', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
    ]
