# Generated by Django 4.1.6 on 2023-02-12 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsersAndProfile', '0007_profile_asi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='asi',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
