# Generated by Django 4.1.6 on 2023-02-12 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsersAndProfile', '0008_alter_profile_asi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='year',
            field=models.CharField(blank=True, choices=[('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025'), ('2026', '2026'), ('2027', '2027'), ('2028', '2028'), ('2029', '2029'), ('2030', '2030')], default='2023', max_length=20),
        ),
    ]
