# Generated by Django 4.1.6 on 2023-02-12 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UsersAndProfile', '0006_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodechefDetail',
            fields=[
                ('date', models.DateField(auto_now=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='UsersAndProfile.profile')),
                ('global_rank', models.PositiveIntegerField(blank=True, null=True)),
                ('badges', models.JSONField(blank=True, null=True)),
                ('contest_participated_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('problems_solved', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CodeforcesDetail',
            fields=[
                ('date', models.DateField(auto_now=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='UsersAndProfile.profile')),
                ('friendOfCount', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('contestRating', models.PositiveIntegerField(blank=True, null=True)),
                ('totalProblemSolved', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('rank', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GithubDetail',
            fields=[
                ('date', models.DateField(auto_now=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='UsersAndProfile.profile')),
                ('no_of_repositories', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('no_of_followers', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('no_of_following', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('tech_stack', models.JSONField(blank=True, null=True)),
                ('own_repo', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HackerrankDetail',
            fields=[
                ('date', models.DateField(auto_now=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='UsersAndProfile.profile')),
                ('followers_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('score_lang', models.PositiveIntegerField(blank=True, null=True)),
                ('badges', models.JSONField(blank=True, null=True)),
                ('certificates', models.JSONField(blank=True, null=True)),
                ('score_elo', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LeetcodeDetail',
            fields=[
                ('date', models.DateField(auto_now=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='UsersAndProfile.profile')),
                ('no_easy_qns', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('no_medium_qns', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('no_difficult_qns', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('overall_raking', models.PositiveIntegerField(blank=True, null=True)),
                ('no_of_submissions', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('languages', models.JSONField(blank=True, null=True)),
                ('skills_advanced', models.JSONField(blank=True, null=True)),
                ('skills_intermediate', models.JSONField(blank=True, null=True)),
                ('skills_fundamental', models.JSONField(blank=True, null=True)),
                ('contests', models.JSONField(blank=True, null=True)),
                ('badges', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LinkedInDetail',
            fields=[
                ('date', models.DateField(auto_now=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='UsersAndProfile.profile')),
                ('img_url', models.CharField(blank=True, max_length=200, null=True)),
                ('aboutus', models.TextField(blank=True, null=True)),
                ('headline', models.CharField(blank=True, max_length=250, null=True)),
                ('geoLocationName', models.CharField(blank=True, max_length=200, null=True)),
                ('experience', models.JSONField(blank=True, null=True)),
                ('education', models.JSONField(blank=True, null=True)),
                ('certifications', models.JSONField(blank=True, null=True)),
                ('projects', models.JSONField(blank=True, null=True)),
                ('honors', models.JSONField(blank=True, null=True)),
                ('publications', models.JSONField(blank=True, null=True)),
                ('skills', models.JSONField(blank=True, null=True)),
                ('connectionsCount', models.SmallIntegerField(blank=True, null=True)),
            ],
        ),
    ]
