# Generated by Django 4.1.6 on 2023-02-13 13:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UsersAndProfile', '0009_alter_newuser_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('date', models.DateField(default=datetime.datetime(2023, 2, 13, 18, 55, 5, 289235))),
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('officetype', models.CharField(blank=True, choices=[('CSBS', 'CSBS'), ('ASI', 'Anaytics Society of India')], default='CSBS', max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('winner1', models.CharField(blank=True, max_length=100, null=True)),
                ('winner2', models.CharField(blank=True, max_length=100, null=True)),
                ('winner3', models.CharField(blank=True, max_length=100, null=True)),
                ('winner4', models.CharField(blank=True, max_length=100, null=True)),
                ('winner5', models.CharField(blank=True, max_length=100, null=True)),
                ('imageUrl1', models.URLField(blank=True, max_length=400, null=True)),
                ('imageUrl2', models.URLField(blank=True, max_length=400, null=True)),
                ('imageUrl3', models.URLField(blank=True, max_length=400, null=True)),
                ('imageUrl4', models.URLField(blank=True, max_length=400, null=True)),
                ('imageUrl5', models.URLField(blank=True, max_length=400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OfficeBearer',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='UsersAndProfile.profile')),
                ('position', models.CharField(blank=True, max_length=70, null=True)),
                ('img', models.URLField(blank=True, max_length=400, null=True)),
                ('rank', models.SmallIntegerField(default=20, null=True)),
                ('present_academic_year', models.CharField(blank=True, choices=[('2020-2021', '2020-2021'), ('2021-2022', '2021-2022'), ('2022-2023', '2022-2023'), ('2023-2024', '2023-2024'), ('2024-2025', '2024-2025'), ('2025-2026', '2025-2026'), ('2026-2027', '2026-2027'), ('2027-2028', '2027-2028'), ('2028-2029', '2028-2029'), ('2029-2030', '2029-2030'), ('2030-2031', '2030-2031')], default='2022-2023', max_length=20)),
                ('officetype', models.CharField(blank=True, choices=[('CSBS', 'CSBS'), ('ASI', 'Anaytics Society of India')], default='CSBS', max_length=100)),
            ],
        ),
    ]
