# Generated by Django 4.1.6 on 2023-02-13 13:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssociationAndEvents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 2, 13, 18, 55, 19, 471437)),
        ),
    ]
