# Generated by Django 4.1.6 on 2023-02-14 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AssociationAndEvents', '0003_alter_event_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='officebearer',
            old_name='id',
            new_name='profile',
        ),
    ]
