# Generated by Django 4.1.6 on 2023-03-02 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssociationAndEvents', '0004_rename_id_officebearer_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officebearer',
            name='officetype',
            field=models.CharField(blank=True, choices=[('CSBSA', 'CSBSA'), ('ASI', 'Anaytics Society of India')], default='CSBSA', max_length=100),
        ),
    ]
